### ISSUE TITLE
Accomodation checklist

### ISSUE THREAD

**Issue by cheapjack** [cheapjack/oksparks#41]

**Comment by cheapjack** [comment]
- [ ] bedding
- [ ] food
  - [x] garlic, 3 bulbs
  - [x] 1 kg bag of short grain rice
  - [x] 1 tin of chickpeas
  - [x] 2 bags of dried pasta (tortiglioni)
  - [x] 1 bag of Korean chicken stew seasoning
  - [x] dried seaweed
  - [x] 1 tin of chopped tomatoes 
- [ ] Omnivore Food
  - [ ] Black Pudding
  - [ ] Chocolate Cake
  - [ ] Bacon
  - [ ] Eggs
  - [ ] Bread
  - [ ] Muesli

**Comment by cheapjack** [comment]
@gkboulter do we need to take any bedding over to Coniston this time round?

**Comment by gkboulter** [comment]
Same again if possible - sheet / pillow case / duvet cover. They have some there that we can use if we wash them at the end of the stay though.
